# -*- coding: utf-8 -*-
"""Generate the reference list and the BibTeX file from refs.json.

`refs.json` is the only place a citation is written down. The numbered list in the report
and `refs.bib` for the preprint are both produced from it, so the two cannot drift apart.
An earlier plan was to keep both by hand and compare them; comparison catches a mismatch
but not two copies edited wrong the same way.

Three rules the generator follows, in code rather than in a convention:

* A field that is null is omitted. Nothing is completed, inferred or looked up here.
* `verified_from` must be present. If nobody recorded where a page number came from, the
  entry does not go out.
* A non-empty `caveat` becomes a comment on the BibTeX entry. Dropping it silently is a
  failure, because the caveats are the places where an obvious-looking field is wrong.

`verbatim` holds the exact published text of an entry, newlines included, and is emitted
unchanged when present. It exists for entries whose wording is fixed outside this file. No
entry uses it now: entries 1 to 8 did, to keep their published form frozen, until keeping
them shorter than the rest started to read as unfinished work rather than as restraint.

`conditional_on` names an experiment that has not been run. Those entries are skipped, so
the list never cites work for a result that does not exist.

Usage:
    python tools/make_refs.py                 write refs.bib, print the list
    python tools/make_refs.py --into FILE     also inject the list into FILE
    python tools/make_refs.py --check FILE    regenerate and diff; non-zero if either differs
"""
import argparse
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFS = ROOT / "refs.json"
BIB = ROOT / "refs.bib"
BEGIN = "<!-- BEGIN references (generated by tools/make_refs.py; do not edit by hand) -->"
END = "<!-- END references -->"
LF = chr(10)
WIDTH = 88

# Experiments that have been run. An entry whose conditional_on is not in here is skipped.
RUN = set()


def wrap(text, first, cont):
    """Greedy wrap. `first` already ends in a space, so the first word joins it directly."""
    words = text.split()
    lines, cur = [], first + words[0]
    for w in words[1:]:
        if len(cur) + 1 + len(w) > WIDTH:
            lines.append(cur)
            cur = cont + w
        else:
            cur += " " + w
    lines.append(cur)
    return LF.join(lines)


def authors_text(r):
    a = r.get("authors") or []
    return ", ".join(a)


def render_entry(r):
    if r.get("verbatim"):
        return r["verbatim"]
    bits = ["%s (%s)." % (authors_text(r), r["year"]), r["title"] + "."]
    tail = []
    # "arXiv preprint" as a venue plus an arXiv identifier says the same thing twice; the
    # identifier is the useful half. The field stays in refs.json because BibTeX wants it.
    if r.get("venue") and not (r["venue"] == "arXiv preprint" and r.get("arxiv")):
        tail.append(r["venue"])
    if r.get("publisher"):
        tail.append(r["publisher"])
    # A proceedings volume reads "PMLR 119" or "Lecture Notes in Computer Science 6314";
    # a journal volume reads "98" or "57(7)". Same two fields, two conventions.
    if r.get("series"):
        tail.append("%s %s" % (r["series"], r["volume"]) if r.get("volume")
                    else r["series"])
    elif r.get("volume"):
        tail.append("%s(%s)" % (r["volume"], r["number"]) if r.get("number")
                    else str(r["volume"]))
    if r.get("pages"):
        tail.append(str(r["pages"]))
    if tail:
        bits.append(", ".join(tail) + ".")
    # Identifiers, each its own sentence. `note` carries one that is not a DOI: entry 1 is
    # in press and its PII is the only identifier it has, so dropping it would leave that
    # entry with no way to look it up.
    ids = []
    if r.get("doi"):
        ids.append("doi:%s" % r["doi"])
    if r.get("openreview"):
        ids.append("OpenReview %s" % r["openreview"])
    if r.get("arxiv"):
        ids.append("arXiv:%s" % r["arxiv"])
    if r.get("note"):
        ids.append(r["note"])
    if ids:
        bits.append(". ".join(ids))
    body = " ".join(bits).replace("..", ".")
    # Continuation lines line up under the text, so the indent follows the number width.
    first = "%d. " % r["n"]
    return wrap(body, first, " " * len(first))


def render_bibtex(r):
    out = ["@%s{%s," % (r["entry_type"], r["bibtex_key"])]
    au = r.get("authors_bibtex") or " and ".join(r.get("authors") or [])
    out.append("  author = {%s}," % au)
    out.append("  title = {%s}," % r["title"])
    key = "journal" if r["entry_type"] == "article" else "booktitle"
    if r.get("venue"):
        out.append("  %s = {%s}," % (key, r["venue"]))
    for f, name in (("series", "series"), ("publisher", "publisher"),
                    ("volume", "volume"), ("number", "number"), ("pages", "pages")):
        if r.get(f):
            v = str(r[f]).replace("-", "--") if f == "pages" else r[f]
            out.append("  %s = {%s}," % (name, v))
    out.append("  year = {%s}," % r["year"])
    if r.get("doi"):
        out.append("  doi = {%s}," % r["doi"])
    if r.get("arxiv"):
        out.append("  eprint = {%s}, archivePrefix = {arXiv}," % r["arxiv"])
    if r.get("note"):
        out.append("  note = {%s}," % r["note"])
    out[-1] = out[-1].rstrip(",") + "}"
    lines = []
    if r.get("caveat"):
        lines.append("%% %s" % r["caveat"])
    if r.get("source_note"):
        lines.append("%% source: %s" % r["source_note"])
    return LF.join(lines + out)


def load():
    refs = json.load(io.open(REFS, encoding="utf-8"))
    bad = [r["n"] for r in refs if not r.get("verified_from")]
    if bad:
        sys.exit("**refs.json: these entries have no verified_from, so nothing goes out: %s**"
                 % bad)
    kept = [r for r in refs if not r.get("conditional_on")
            or r["conditional_on"] in RUN]
    skipped = [(r["n"], r["conditional_on"]) for r in refs if r not in kept]
    return sorted(kept, key=lambda r: r["n"]), skipped


def build():
    refs, skipped = load()
    listing = (LF * 2).join(render_entry(r) for r in refs)
    bib = (LF * 2).join(render_bibtex(r) for r in refs) + LF
    return refs, skipped, listing, bib


def inject(path, listing):
    s = io.open(path, encoding="utf-8").read()
    if BEGIN not in s or END not in s:
        sys.exit("**%s has no reference markers; add %s / %s around the list**"
                 % (path, BEGIN, END))
    head, rest = s.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + BEGIN + LF + listing + LF + END + tail


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--into", help="markdown file to inject the list into")
    ap.add_argument("--check", help="markdown file to check against, writing nothing")
    args = ap.parse_args()

    refs, skipped, listing, bib = build()
    print("  %d entries; %d skipped as conditional on an experiment not run %s"
          % (len(refs), len(skipped), skipped))
    n_cav = sum(1 for r in refs if r.get("caveat"))
    print("  %d carry a caveat, and every one of them is a comment in refs.bib" % n_cav)
    for r in refs:
        if r.get("caveat") and ("%% %s" % r["caveat"]) not in bib:
            sys.exit("**caveat on entry %d was dropped from the BibTeX**" % r["n"])

    if args.check:
        problems = []
        cur_bib = io.open(BIB, encoding="utf-8").read() if BIB.exists() else None
        if cur_bib != bib:
            problems.append("refs.bib differs from what refs.json generates")
        target = io.open(args.check, encoding="utf-8").read()
        if inject(args.check, listing) != target:
            problems.append("%s reference list differs from what refs.json generates"
                            % args.check)
        for p in problems:
            print("  **%s**" % p)
        print("  " + ("both match refs.json" if not problems else "regenerate them"))
        sys.exit(1 if problems else 0)

    io.open(BIB, "w", encoding="utf-8", newline=LF).write(bib)
    print("  wrote %s" % BIB)
    if args.into:
        # Build the new text before opening the file for writing, and never in the same
        # expression. `open(path, "w")` truncates the moment it is evaluated, and Python
        # evaluates it before the argument it is passed; if the argument then reads that
        # same file and fails, the file is already empty. That is not hypothetical: it
        # destroyed the report source once, and the traceability layer in it was not
        # recoverable from the rendered copy.
        new = inject(args.into, listing)
        io.open(args.into, "w", encoding="utf-8", newline=LF).write(new)
        print("  injected the reference list into %s" % args.into)


if __name__ == "__main__":
    main()
